#!usr/bin/python3
def suma(sumando1, sumando2):
    print("Resultado suma:", sumando1 + sumando2)

def resta(minuendo, sustraendo):
    print("Resultado resta:", minuendo - sustraendo)

def multiplicación(factor1, factor2):
    print("Resultado multiplicación:", factor1 * factor2)

def potencia(base, exponente):
    print("Resultado potencia:", base ** exponente)


print("-----------------")
suma(3, 8)
print("-----------------")
resta(5, 11)
print("-----------------")
multiplicación(4, 8)
print("-----------------")
potencia(5, 2)
print("-----------------")
