#!usr/bin/python3
def suma(sumando1, sumando2):
    print("Resultado suma:", sumando1 + sumando2)


def resta(minuendo, sustraendo):
    print("Resultado resta:", minuendo - sustraendo)


def multiplicación(factor1, factor2):
    print("Resultado multiplicación:", factor1 * factor2)


def potencia(base, exponente):
    if (base == 0 and exponente < 0):
        print("Error: la division entre 0 no esta definida")

    else:
        print("Resultado potencia:", base ** exponente)


print("-----------------")
suma(3, 8)
print("-----------------")
resta(-5, 11)
print("-----------------")
multiplicación(4, 0.9)
print("-----------------")
potencia(0, 0)
print("-----------------")
